//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst_EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlightRoute()
        {
            this.FlightPlans = new HashSet<FlightPlan>();
        }
    
        public int FlightRoute_Id { get; set; }
        public int From_Dest { get; set; }
        public int To_Dest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightPlan> FlightPlans { get; set; }
        public virtual MyAirport MyAirport { get; set; }
        public virtual MyAirport MyAirport1 { get; set; }
    }
}
